[package]
name = "wireguard-uapi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = { version = "0.27.1", default-features = false, features = ["socket"] }

[build-dependencies]
bindgen = "0.66.1"
